server:
  port: 9001
spring:
  application:
    name: user-Server-RPCHTTP
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: heima121
    username: heima121
    password: heima121
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springbootdb
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
sms:
  ip: lisi
